<?php

/**
 * @file
 * Hello World modifications.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;

/**
 * Impelements hook_theme().
 */
function hello_world_theme() {
  return [
    'hello_world_content_start' => [
      // Variables or Render Element is required by hook_theme().
      'variables' => [],
    ],
  ];
}

/**
 * Implements hook_entity_extra_field_info().
 */
function hello_world_entity_extra_field_info() {
  return [
    'node' => [
      'hello_world_article' => [
        'display' => [
          'hello_world_content_start' => [
            'label' => t('Content Start'),
            'description' => t('Informs the user of where the content starts.'),
            'weight' => -1,
            'visible' => TRUE,
          ],
        ],
      ],
    ],
  ];
}

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function hello_world_node_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  if ($entity->getEntityTypeId() == 'node' && $entity->bundle() == 'hello_world_article' && $display->getComponent('hello_world_content_start')) {
    $build['hello_world_content_start'] = [
      '#theme' => 'hello_world_content_start',
    ];
  }
}
